"""Multi-format universal document loader.

Extracts plain text, structured sections, and page coordinates across:
PDF, DOCX, TXT, MD, CSV, JSON, HTML, YAML.
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
import re
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml


EMOJI_PATTERN = re.compile(
    r"["
    r"\U00010000-\U0010ffff"
    r"\u2600-\u27bf"
    r"\u2300-\u23ff"
    r"\u2b00-\u2bff"
    r"]+",
    flags=re.UNICODE,
)


def strip_emojis(text: str) -> str:
    """Removes all emojis and pictographic symbols from document text."""
    if not text:
        return ""
    return EMOJI_PATTERN.sub("", text)


@dataclass
class LoadedDocument:
    doc_id: str
    filename: str
    file_type: str
    raw_content: str
    pages: List[Tuple[int, str]] = field(default_factory=list)  # (page_no, text)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def total_pages(self) -> int:
        return max(1, len(self.pages))


class DocumentLoader:
    """Universal loader that auto-detects file format and extracts structured text."""

    SUPPORTED_EXTENSIONS = {
        ".pdf", ".docx", ".doc", ".txt", ".md", ".markdown",
        ".csv", ".json", ".jsonl", ".yaml", ".yml", ".html", ".htm"
    }

    @classmethod
    def is_supported(cls, file_path: str | Path) -> bool:
        ext = Path(file_path).suffix.lower()
        return ext in cls.SUPPORTED_EXTENSIONS

    def load(self, file_path: str | Path, custom_metadata: Optional[Dict[str, Any]] = None) -> LoadedDocument:
        p = Path(file_path)
        if not p.exists():
            raise FileNotFoundError(f"Document file not found: {p}")

        ext = p.suffix.lower()
        doc_id = hashlib.sha256(f"{p.name}_{p.stat().st_size}".encode("utf-8")).hexdigest()[:12]
        meta = {
            "source_path": str(p),
            "size_bytes": p.stat().st_size,
            "extension": ext,
            **(custom_metadata or {})
        }

        if ext == ".pdf":
            pages, text = self._load_pdf(p)
        elif ext in {".docx", ".doc"}:
            pages, text = self._load_docx(p)
        elif ext in {".txt", ".log"}:
            pages, text = self._load_txt(p)
        elif ext in {".md", ".markdown"}:
            pages, text = self._load_markdown(p)
        elif ext == ".csv":
            pages, text = self._load_csv(p)
        elif ext in {".json", ".jsonl"}:
            pages, text = self._load_json(p)
        elif ext in {".yaml", ".yml"}:
            pages, text = self._load_yaml(p)
        elif ext in {".html", ".htm"}:
            pages, text = self._load_html(p)
        else:
            # Universal text fallback
            pages, text = self._load_txt(p)

        # Sanitize all text to ensure zero emojis in index
        clean_text = strip_emojis(text)
        clean_pages = [(p_no, strip_emojis(p_text)) for p_no, p_text in pages]

        return LoadedDocument(
            doc_id=doc_id,
            filename=p.name,
            file_type=ext.lstrip("."),
            raw_content=clean_text,
            pages=clean_pages,
            metadata=meta,
        )

    def _load_pdf(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        pages = []
        full_text = []

        # Try pypdf first
        try:
            import pypdf
            reader = pypdf.PdfReader(str(path))
            for idx, page in enumerate(reader.pages):
                extracted = page.extract_text() or ""
                if extracted.strip():
                    pages.append((idx + 1, extracted.strip()))
                    full_text.append(extracted.strip())
            if pages:
                return pages, "\n\n".join(full_text)
        except Exception:
            pass

        # Fallback 1: inspect raw stream lines if generated by minimal PDF writers
        try:
            raw_bytes = path.read_bytes()
            # Look for BT ... ET text streams
            matches = re.findall(rb"BT\s*(.*?)\s*ET", raw_bytes, re.DOTALL)
            if matches:
                extracted_lines = []
                for m in matches:
                    # extract parenthesis strings (text)
                    t_matches = re.findall(rb"\((.*?)\)", m)
                    for tm in t_matches:
                        extracted_lines.append(tm.decode("latin-1", errors="replace"))
                if extracted_lines:
                    text = "\n".join(extracted_lines)
                    return [(1, text)], text
        except Exception:
            pass

        # Fallback 2: text decode
        text = path.read_text(encoding="utf-8", errors="replace")
        return [(1, text)], text

    def _load_docx(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        # Try python-docx
        try:
            import docx
            doc = docx.Document(str(path))
            paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
            for table in doc.tables:
                for row in table.rows:
                    row_text = " | ".join(cell.text.strip() for cell in row.cells if cell.text.strip())
                    if row_text:
                        paragraphs.append(row_text)
            text = "\n\n".join(paragraphs)
            return [(1, text)], text
        except Exception:
            pass

        # Fallback: unzip and parse word/document.xml
        try:
            with zipfile.ZipFile(path) as z:
                xml_content = z.read("word/document.xml").decode("utf-8", errors="replace")
                text = re.sub(r"<[^>]+>", " ", xml_content)
                text = re.sub(r"\s+", " ", text).strip()
                return [(1, text)], text
        except Exception:
            text = path.read_text(encoding="utf-8", errors="replace")
            return [(1, text)], text

    def _load_txt(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        text = path.read_text(encoding="utf-8", errors="replace").strip()
        return [(1, text)], text

    def _load_markdown(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        text = path.read_text(encoding="utf-8", errors="replace").strip()
        # Pages could be demarcated by horizontal rules '---'
        splits = re.split(r"\n---+\n", text)
        pages = [(i + 1, s.strip()) for i, s in enumerate(splits) if s.strip()]
        return pages or [(1, text)], text

    def _load_csv(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        rows_text = []
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)
            header = None
            for row in reader:
                if not row or not any(row):
                    continue
                if header is None:
                    header = row
                    rows_text.append(f"Headers: {', '.join(header)}")
                else:
                    item_str = ", ".join(f"{h}: {val}" for h, val in zip(header, row) if val.strip())
                    rows_text.append(f"Record: {item_str}")

        text = "\n".join(rows_text)
        return [(1, text)], text

    def _load_json(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        raw = path.read_text(encoding="utf-8", errors="replace").strip()
        if path.suffix.lower() == ".jsonl":
            lines = [json.loads(line) for line in raw.split("\n") if line.strip()]
            text = json.dumps(lines, indent=2)
        else:
            data = json.loads(raw)
            text = json.dumps(data, indent=2)
        return [(1, text)], text

    def _load_yaml(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        raw = path.read_text(encoding="utf-8", errors="replace").strip()
        data = yaml.safe_load(raw)
        text = yaml.dump(data, default_flow_style=False)
        return [(1, text)], text

    def _load_html(self, path: Path) -> Tuple[List[Tuple[int, str]], str]:
        raw = path.read_text(encoding="utf-8", errors="replace").strip()
        # Remove script and style elements
        cleaned = re.sub(r"<(script|style)[^>]*>.*?</\1>", "", raw, flags=re.DOTALL | re.IGNORECASE)
        # Convert header tags to markdown-like headers
        cleaned = re.sub(r"<h[1-6][^>]*>(.*?)</h[1-6]>", r"\n# \1\n", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"<p[^>]*>", "\n\n", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"<br\s*/?>", "\n", cleaned, flags=re.IGNORECASE)
        text = re.sub(r"<[^>]+>", " ", cleaned)
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n\s*\n+", "\n\n", text).strip()
        return [(1, text)], text
